#!/usr/bin/env python3
"""
Figure 6 data builders.

Self-contained script that reads ONLY from pnc.preproc.loader and builds the three
cached datasets Fig 6 (figures/main/fig6_benchmarking.py) consumes:

  1. build_separation() -> <out>/fig6_separation.pkl   (Q1 model separation)
  2. build_efficiency() -> <out>/fig6_efficiency.pkl    (Q2 natural-vs-accentuated)
  3. build_pair(a, b, ch) -> <out>/fig6_pair_<A>__<B>__ch<ch>.pkl  (worked example)

Predictions are the faithful pred_resp (resnet50_clip fix + firing-floor clamp at
comparison). The worked-example pair is built for both presets used by the figure
(rn50: resnet50 vs resnet50_robust; clip: resnet50_clip vs clipag_vitb32), channel 2.

    python scripts/preprocessing/build_fig6_caches.py [--out DIR]
"""

import argparse
import os
import pickle
from itertools import combinations

import numpy as np
from scipy import stats

from pnc import paths
from pnc.preproc import loader as L  # noqa: E402

PREPROC_DATA = str(paths.preprocessed_data())
THUMB_DIR_INET = os.path.join(PREPROC_DATA, 'fig6_imagenet_thumbs')

# Canonical 10-model order (loader order); resolved lazily so --help works without data.
class _Models(list):
    def _load(self):
        if not len(self):
            self.extend(L.load_predictions('red')['pred_models'])
        return self
    def __iter__(self):
        return list.__iter__(self._load())
    def __len__(self):
        return list.__len__(self._load())
    def __getitem__(self, i):
        return list.__getitem__(self._load(), i)
    def index(self, *a):
        return list.index(self._load(), *a)


MODELS = _Models()
MONKEYS = ['red', 'paul', 'venus', 'leap', 'three0']
# Adversarially-robust models — used by the 'pooled_minus_robust' condition, which
# drops every stimulus generated by these models so no model can benefit (directly
# or indirectly) from robust-generated probes.
ROBUST_MODELS = {'resnet50_robust', 'clipag_vitb32'}

MIN_PER_CHANNEL = 3      # min stims per (monkey, unit) to compute a per-channel r
CONDITIONS = ['personal', 'pooled', 'pooled_minus_own', 'pooled_minus_robust']
# Violin panels (b/c) show only the "fair" set: (unit,seed,level) cells every model synthesized
# within relerr<=INTERSECT_TAU, so no model's accentuations reach further than another's.
INTERSECT_TAU = 0.02


# ══════════════════════════════════════════════════════════════════════
# 1. model separation  (Q1)
# ══════════════════════════════════════════════════════════════════════

def _separation_records():
    """One record per (monkey, stim, target_unit, predicting_model): floor-clamped
    prediction, measured accentuated response, and same_model / same_channel flags.
    Uses load_predictions per monkey (within-monkey constraint) and _acc_response."""
    records = []
    for monkey in MONKEYS:
        P = L.load_predictions(monkey)
        pred = P['pred']                       # (n_stim, 10, 5)
        pred_models = list(P['pred_models'])
        units = list(P['target_units'])        # this monkey's 5 units
        gm, gu = P['gen_model'], P['gen_unit']
        stim = P['stim']
        resp = {int(u): L._acc_response(monkey, int(u)) for u in units}
        floor = {int(u): L.firing_floor(monkey, int(u)) for u in units}
        ex = L.load_exclusions(monkey)         # intersect = all models synthesized this cell OK
        im = np.asarray(ex['masks'][INTERSECT_TAU]['intersect'], bool)
        inter = {str(ex['stim'][i]): bool(im[i]) for i in range(len(ex['stim']))}
        for s in range(len(stim)):
            sname = stim[s]
            gen_model = str(gm[s])
            gen_unit = int(gu[s])
            in_fair = inter.get(str(sname), False)
            for ui, unit in enumerate(units):
                r = resp[int(unit)]
                if sname not in r:
                    continue
                response = r[sname]
                for mi, pm in enumerate(pred_models):
                    prediction = float(max(pred[s, mi, ui], floor[int(unit)]))
                    records.append(dict(
                        monkey=monkey, target_unit=int(unit), gen_unit=gen_unit,
                        generating_model=gen_model, predicting_model=pm,
                        prediction=prediction, response=response,
                        same_model=(pm == gen_model),
                        same_channel=(gen_unit == int(unit)), intersect=in_fair))
    return records


def _per_channel_rs(recs):
    """Per-(monkey,target_unit) Pearson r for each predicting model (>=3 stims, nonzero std)."""
    out = {}
    for m in MODELS:
        rs = []
        groups = {}
        for rec in recs:
            if rec['predicting_model'] != m:
                continue
            groups.setdefault((rec['monkey'], rec['target_unit']), []).append(rec)
        for lst in groups.values():
            if len(lst) < MIN_PER_CHANNEL:
                continue
            x = np.array([rec['prediction'] for rec in lst], float)
            y = np.array([rec['response'] for rec in lst], float)
            if x.std() == 0 or y.std() == 0:
                continue
            rs.append(float(stats.pearsonr(x, y)[0]))
        out[m] = np.array(rs, dtype=float)
    return out


def _pooled_r(recs):
    out = {}
    for m in MODELS:
        x = np.array([rec['prediction'] for rec in recs
                      if rec['predicting_model'] == m], float)
        y = np.array([rec['response'] for rec in recs
                      if rec['predicting_model'] == m], float)
        if len(x) < 10 or x.std() == 0 or y.std() == 0:
            out[m] = np.nan
        else:
            out[m] = float(stats.pearsonr(x, y)[0])
    return out


def _violin_samples(all_recs):
    """Per-model z-scored predictions for two subsets: 'SM-SC' (same_model &
    same_channel) and 'full' (all).  z uses GLOBAL mu/sigma over ALL records'
    prediction (so the two subsets share units).  ALL points — no subsampling."""
    all_pred = np.array([rec['prediction'] for rec in all_recs], float)
    mu = float(all_pred.mean())
    sd = float(all_pred.std() + 1e-9)
    fair = [rec for rec in all_recs if rec.get('intersect')]      # equal (unit,seed,level) set per model
    subsets = {
        'SM-SC': [rec for rec in fair if rec['same_model'] and rec['same_channel']],
        'full': fair,
    }
    out = {'_zparams': dict(mu=mu, sd=sd)}
    for key, sub in subsets.items():
        per_model = {}
        for m in MODELS:
            preds = np.array([rec['prediction'] for rec in sub
                              if rec['predicting_model'] == m], float)
            per_model[m] = (preds - mu) / sd
        out[key] = per_model
    return out


def build_separation(out_dir=PREPROC_DATA):
    recs = _separation_records()
    # panel a (per-channel / pooled r) uses ALL data; b/c violins use the fair set (_violin_samples).
    subs = {
        'personal': [r for r in recs if r['same_model'] and r['same_channel']],
        'pooled': recs,
        'pooled_minus_own': [r for r in recs if not r['same_model']],
        'pooled_minus_robust': [r for r in recs
                                if r['generating_model'] not in ROBUST_MODELS],
    }
    n_images = {}
    for k, v in subs.items():
        n_images[k] = len({(r['monkey'], r['gen_unit'], r['generating_model'])
                           for r in v})
    per_channel = {k: _per_channel_rs(v) for k, v in subs.items()}
    pooled = {k: _pooled_r(v) for k, v in subs.items()}
    violin_samples = _violin_samples(recs)
    out = dict(per_channel=per_channel, pooled=pooled, n_images=n_images,
               n_records={k: len(v) for k, v in subs.items()},
               violin_samples=violin_samples)
    cache = os.path.join(out_dir, 'fig6_separation.pkl')
    with open(cache, 'wb') as f:
        pickle.dump(out, f)
    print(f'separation cached -> {cache}')
    return out


# ══════════════════════════════════════════════════════════════════════
# 2. natural-vs-accentuated efficiency  (Q2)
# ══════════════════════════════════════════════════════════════════════

def _efficiency_arrays():
    """Assemble the efficiency substrate from the loader:
      inet      (50000, 25, 10)   ImageNet predictions (raw)
      inet_std  (50000, 25, 10)   standardized per (channel, model) by ImageNet P1/P99
      per-channel accentuated |A-B| pieces, computed within each channel's monkey.
    """
    IN = L.load_imagenet()
    inet = IN['imagenet_predictions'].astype(np.float64)   # (50000, 25, 10)
    unit_monkeys = np.array(IN['unit_monkeys'], dtype=str)
    unit_ids = np.array(IN['unit_ids'], dtype=int)
    in_models = list(IN['models'])
    # Reindex ImageNet model axis to the canonical MODELS order.
    order = [in_models.index(m) for m in MODELS]
    inet = inet[:, :, order]

    # per-(channel, model) standardization by ImageNet 1-99 pct range.
    #   inet_p1 = np.percentile(inet, 1, axis=0); inet_p99 = ...; rng guard 1e-9.
    inet_p1 = np.percentile(inet, 1, axis=0)               # (25, 10)
    inet_p99 = np.percentile(inet, 99, axis=0)
    inet_rng = inet_p99 - inet_p1
    inet_rng = np.where(inet_rng > 1e-9, inet_rng, 1.0)
    inet_std = (inet - inet_p1[None, :, :]) / inet_rng[None, :, :]

    # Accentuated predictions per channel (within-monkey constraint): for each of
    # the 25 channels we hold model x this-channel-monkey preds for that monkey's
    # accentuated stims, plus each stim's generating model / unit, so we can pull
    # the per-pair subset (gen_unit == this channel's unit & gen_model in {A,B}).
    per_ch = []   # list of 25 dicts: pred_std (n_stim_monkey,10), gen_model, gen_unit
    for c in range(25):
        monkey = str(unit_monkeys[c])
        unit = int(unit_ids[c])
        P = L.load_predictions(monkey)
        pmods = list(P['pred_models'])
        munits = list(P['target_units'])
        ui = munits.index(unit)
        morder = [pmods.index(m) for m in MODELS]
        pred_ch = P['pred'][:, :, ui][:, morder].astype(np.float64)   # (n_stim, 10)
        pred_ch_std = (pred_ch - inet_p1[None, c, :]) / inet_rng[None, c, :]
        per_ch.append(dict(pred_std=pred_ch_std,
                           gen_model=np.array(P['gen_model'], dtype=str),
                           gen_unit=np.array(P['gen_unit'], dtype=int),
                           unit=unit))
    return dict(inet=inet, inet_std=inet_std, unit_monkeys=unit_monkeys,
                unit_ids=unit_ids, per_ch=per_ch)


def build_efficiency(out_dir=PREPROC_DATA):
    A = _efficiency_arrays()
    inet = A['inet']
    inet_std = A['inet_std']
    unit_monkeys = A['unit_monkeys']
    unit_ids = A['unit_ids']
    per_ch = A['per_ch']

    pairs = list(combinations(range(len(MODELS)), 2))     # 45 unordered pairs
    n_pairs_total = 25 * len(pairs)                        # 1125 combos

    # ── budget grids ──────────────────────────────────────────────────
    #   k_grid_inet = logspace(2..50000, 30); k_grid_acc = logspace(2..220, 20).
    MAX_K_INET = inet.shape[0]      # 50000
    MAX_K_ACC = 220                 # 110 stims x 2 generators per pair
    k_grid_inet = np.unique(np.round(np.logspace(
        np.log10(2), np.log10(MAX_K_INET), 30)).astype(int))
    k_grid_acc = np.unique(np.round(np.logspace(
        np.log10(2), np.log10(MAX_K_ACC), 20)).astype(int))

    inet_budget = np.full((len(k_grid_inet), n_pairs_total), np.nan)
    inet_rand_budget = np.full((len(k_grid_inet), n_pairs_total), np.nan)
    acc_budget = np.full((len(k_grid_acc), n_pairs_total), np.nan)

    # ── per-combo violin scalars (BUDGET=220, mean |A-B|) ──────────────
    BUDGET = 220
    inet_group_top = np.full(n_pairs_total, np.nan)    # mean(top-220)  (standardized)
    inet_group_disp = np.full(n_pairs_total, np.nan)   # mean(random-220)
    acc_group_disp = np.full(n_pairs_total, np.nan)    # mean(acc set)  (>=10 else nan)

    n_acc_ge = 0
    rng_f = np.random.default_rng(0)   # budget random order (seed 0)
    rng_e = np.random.default_rng(0)   # violin random-220 (seed 0)

    group_i = 0
    for col_ch in range(25):
        ch_pred_std = per_ch[col_ch]['pred_std']
        ch_gen_model = per_ch[col_ch]['gen_model']
        ch_gen_unit = per_ch[col_ch]['gen_unit']
        ch_unit = per_ch[col_ch]['unit']
        for mi, mj in pairs:
            # ImageNet |A-B| on standardized preds (inet_std).
            diff_inet = np.abs(inet_std[:, col_ch, mi] - inet_std[:, col_ch, mj])
            s_inet = np.sort(diff_inet)[::-1]
            perm = rng_f.permutation(len(diff_inet))
            rand_order = diff_inet[perm]
            for ki, k in enumerate(k_grid_inet):
                if k <= len(s_inet):
                    inet_budget[ki, group_i] = float(np.mean(s_inet[:k]))
                    inet_rand_budget[ki, group_i] = float(np.mean(rand_order[:k]))

            # violin scalars: mean(top-220), mean(random-220).
            top_idx = np.argsort(diff_inet)[::-1][:BUDGET]
            inet_group_top[group_i] = float(np.mean(diff_inet[top_idx]))
            rand_idx = rng_e.choice(len(diff_inet), size=BUDGET, replace=False)
            inet_group_disp[group_i] = float(np.mean(diff_inet[rand_idx]))

            # Accentuated: stims with gen_unit == this channel's unit and
            # gen_model in {A, B} (within this channel's monkey). 110 + 110.
            mask = ((ch_gen_unit == ch_unit)
                    & ((ch_gen_model == MODELS[mi])
                       | (ch_gen_model == MODELS[mj])))
            if mask.sum() >= 2:
                diff_acc = np.abs(ch_pred_std[mask, mi] - ch_pred_std[mask, mj])
                s_acc = np.sort(diff_acc)[::-1]
                for ki, k in enumerate(k_grid_acc):
                    if k <= len(s_acc):
                        acc_budget[ki, group_i] = float(np.mean(s_acc[:k]))
            if mask.sum() >= 10:
                diff_acc = np.abs(ch_pred_std[mask, mi] - ch_pred_std[mask, mj])
                acc_group_disp[group_i] = float(np.mean(diff_acc))
                n_acc_ge += 1
            group_i += 1

    # ── 10x10 model-pair similarity heatmaps, averaged across 25 channels ──
    n_models = len(MODELS)
    heatmap_inet_per_exp = np.full((25, n_models, n_models), np.nan)
    heatmap_smsc_per_exp = np.full((25, n_models, n_models), np.nan)
    for c in range(25):
        preds = inet[:, c, :]
        if np.std(preds, axis=0).min() > 0:
            heatmap_inet_per_exp[c] = np.corrcoef(preds.T)
        ch_pred = per_ch[c]['pred_std']
        ch_gen_model = per_ch[c]['gen_model']
        ch_gen_unit = per_ch[c]['gen_unit']
        ch_unit = per_ch[c]['unit']
        for mi in range(n_models):
            for mj in range(n_models):
                mask = ((ch_gen_unit == ch_unit)
                        & ((ch_gen_model == MODELS[mi])
                           | (ch_gen_model == MODELS[mj])))
                if int(mask.sum()) < 10:
                    continue
                a = ch_pred[mask, mi]
                b = ch_pred[mask, mj]
                if np.std(a) == 0 or np.std(b) == 0:
                    continue
                heatmap_smsc_per_exp[c, mi, mj] = float(stats.pearsonr(a, b)[0])
    heatmap_inet_avg = np.nanmean(heatmap_inet_per_exp, axis=0)
    heatmap_smsc_avg = np.nanmean(heatmap_smsc_per_exp, axis=0)

    out = dict(
        inet_group_top=inet_group_top,
        inet_group_disp=inet_group_disp,
        acc_group_disp=acc_group_disp,
        k_grid=k_grid_inet,
        k_grid_acc=k_grid_acc,
        inet_budget=inet_budget,
        inet_rand_budget=inet_rand_budget,
        acc_budget=acc_budget,
        unit_monkeys=unit_monkeys,
        unit_ids=unit_ids,
        heatmap_inet_avg=heatmap_inet_avg,
        heatmap_smsc_avg=heatmap_smsc_avg,
    )
    cache = os.path.join(out_dir, 'fig6_efficiency.pkl')
    with open(cache, 'wb') as f:
        pickle.dump(out, f)
    print(f'efficiency cached -> {cache}')
    return out


# ══════════════════════════════════════════════════════════════════════
# 3. worked-example pair
# ══════════════════════════════════════════════════════════════════════

def build_pair(model_a, model_b, ch=2, out_dir=PREPROC_DATA):
    IN = L.load_imagenet()
    inet = IN['imagenet_predictions'].astype(np.float64)      # (50000, 25, 10)
    in_models = list(IN['models'])
    order = [in_models.index(m) for m in MODELS]
    inet = inet[:, :, order]
    unit_monkeys = np.array(IN['unit_monkeys'], dtype=str)
    unit_ids = np.array(IN['unit_ids'], dtype=int)

    inet_p1 = np.percentile(inet, 1, axis=0)                  # (25, 10)
    inet_p99 = np.percentile(inet, 99, axis=0)
    inet_rng = inet_p99 - inet_p1
    inet_rng = np.where(inet_rng > 1e-9, inet_rng, 1.0)

    mi_A, mi_B = MODELS.index(model_a), MODELS.index(model_b)
    monkey = str(unit_monkeys[ch])
    target_unit = int(unit_ids[ch])
    zf = L.firing_floor(monkey, target_unit)

    P = L.load_predictions(monkey)
    pmods = list(P['pred_models'])
    munits = list(P['target_units'])
    ui = munits.index(target_unit)
    morder = [pmods.index(m) for m in MODELS]
    pred_all = P['pred'][:, :, ui][:, morder].astype(np.float64)   # (n_stim, 10)
    gen_model = np.array(P['gen_model'], dtype=str)
    gen_unit = np.array(P['gen_unit'], dtype=int)
    gen_seed = np.array(P['gen_seed'], dtype=int)
    score_all = np.array(P['score'], dtype=float)

    p1_A, rng_A = float(inet_p1[ch, mi_A]), float(inet_rng[ch, mi_A])
    p1_B, rng_B = float(inet_p1[ch, mi_B]), float(inet_rng[ch, mi_B])

    def _std_A(x):
        return (x - p1_A) / rng_A

    def _std_B(x):
        return (x - p1_B) / rng_B

    def _sweeps_for_model(model_name):
        rows = np.where((gen_model == model_name)
                        & (gen_unit == target_unit))[0]
        sweeps = []
        for sd in sorted(set(gen_seed[rows].tolist())):
            sr = rows[gen_seed[rows] == sd]
            sr = sr[np.argsort(score_all[sr])]           # ascending by level/score
            sweeps.append(dict(
                pred_A=np.maximum(pred_all[sr, mi_A], zf).astype(np.float32),
                pred_B=np.maximum(pred_all[sr, mi_B], zf).astype(np.float32),
                score=np.maximum(score_all[sr], zf).astype(np.float32),
                row_idx=sr))
        for sw in sweeps:
            sw['pred_A_std'] = _std_A(sw['pred_A']).astype(np.float32)
            sw['pred_B_std'] = _std_B(sw['pred_B']).astype(np.float32)
        return sweeps

    sweeps_A = _sweeps_for_model(model_a)
    sweeps_B = _sweeps_for_model(model_b)

    pair = dict(
        channel_label=f'{monkey} ch{target_unit}',
        inet_predA=inet[:, ch, mi_A], inet_predB=inet[:, ch, mi_B],
        inet_predA_std=_std_A(inet[:, ch, mi_A]),
        inet_predB_std=_std_B(inet[:, ch, mi_B]),
        sweeps_A=sweeps_A, sweeps_B=sweeps_B)

    # ImageNet thumbnail prefs — most-controversial images (largest |A-B|),
    # restricted to indices whose thumbnail exists locally.
    N_THUMB = 24
    avail = set(int(os.path.splitext(f)[0]) for f in sorted(os.listdir(THUMB_DIR_INET))
                if f.endswith('.JPEG')) if os.path.isdir(THUMB_DIR_INET) else set()
    inet_diff = inet[:, ch, mi_A] - inet[:, ch, mi_B]
    apref_idx = [int(i) for i in np.argsort(inet_diff)[::-1]
                 if int(i) in avail][:N_THUMB]
    bpref_idx = [int(i) for i in np.argsort(inet_diff)
                 if int(i) in avail][:N_THUMB]

    def _inet_meta(i):
        return dict(idx=int(i),
                    thumb_path=os.path.join(THUMB_DIR_INET, f'{i}.JPEG'),
                    predA=float(inet[i, ch, mi_A]),
                    predB=float(inet[i, ch, mi_B]), diff=float(inet_diff[i]))

    # Accentuated thumbnail prefs — among this pair's 220 sweep stims.
    sw_rows = np.concatenate([s['row_idx'] for s in sweeps_A + sweeps_B])
    sw_diff = pred_all[sw_rows, mi_A] - pred_all[sw_rows, mi_B]
    acc_apref_rows = sw_rows[np.argsort(sw_diff)[::-1][:N_THUMB]]
    acc_bpref_rows = sw_rows[np.argsort(sw_diff)[:N_THUMB]]

    def _acc_meta(r):
        return dict(row=int(r), source_model=str(gen_model[r]),
                    score=float(score_all[r]), unit_id=int(target_unit),
                    predA=float(pred_all[r, mi_A]), predB=float(pred_all[r, mi_B]))

    pair.update(dict(
        inet_apref=[_inet_meta(i) for i in apref_idx],
        inet_bpref=[_inet_meta(i) for i in bpref_idx],
        acc_apref=[_acc_meta(r) for r in acc_apref_rows],
        acc_bpref=[_acc_meta(r) for r in acc_bpref_rows]))

    cache = os.path.join(out_dir,
                         f'fig6_pair_{model_a}__{model_b}__ch{ch}.pkl')
    with open(cache, 'wb') as f:
        pickle.dump(pair, f)
    print(f'pair cached -> {os.path.basename(cache)} '
          f'({len(sweeps_A)}+{len(sweeps_B)} sweeps, {pair["channel_label"]})')
    return pair


# ══════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', default=PREPROC_DATA,
                    help='directory that receives the fig6_*.pkl caches (default: preprocessed_data)')
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    print('=' * 68)
    print('build_separation()')
    print('=' * 68)
    SEP = build_separation(args.out)
    print('\nmodel-separation (SD across per-model mean r, excl. AlexNet):')
    non_alex = [m for m in MODELS if m != 'AlexNet_training_seed_01']
    for cond in CONDITIONS:
        pc = SEP['per_channel'][cond]
        means = np.array([np.nanmean(pc[m]) if len(pc[m]) else np.nan
                          for m in non_alex])
        pooled_rs = np.array([SEP['pooled'][cond][m] for m in non_alex])
        sd_mean = np.nanstd(means, ddof=1)
        sd_pool = np.nanstd(pooled_rs, ddof=1)
        print(f'  {cond:18s} n_imgs={SEP["n_images"][cond]:5d}  '
              f'SD(per-chan mean r)={sd_mean:.3f}  SD(pooled r)={sd_pool:.3f}')
    vs = SEP['violin_samples']
    print('  violin_samples SM-SC total pts:',
          sum(len(vs['SM-SC'][m]) for m in MODELS),
          '| full total pts:', sum(len(vs['full'][m]) for m in MODELS))

    print('\n' + '=' * 68)
    print('build_efficiency()')
    print('=' * 68)
    EFF = build_efficiency(args.out)
    print('  inet_group_top shape:', EFF['inet_group_top'].shape)
    print('  acc_group_disp shape:', EFF['acc_group_disp'].shape)
    print('  inet_budget shape:', EFF['inet_budget'].shape,
          '| acc_budget shape:', EFF['acc_budget'].shape)
    print('  k_grid:', EFF['k_grid'])
    print('  k_grid_acc:', EFF['k_grid_acc'])
    # Paper's point: accentuated mean |A-B| exceeds ImageNet best-k at k=110.
    igt = EFF['inet_group_top']
    agd = EFF['acc_group_disp']
    keep = np.isfinite(igt) & np.isfinite(agd)
    frac = float(np.mean(agd[keep] > igt[keep]))
    print(f'  combos where accentuated mean|A-B| > ImageNet best-220 mean: '
          f'{frac:.3f}  (n={int(keep.sum())})')
    print(f'    ImageNet best-220 mean |A-B| = {np.nanmean(igt):.4f}')
    print(f'    Accentuated  mean |A-B|      = {np.nanmean(agd):.4f}')
    # Budget-curve check at k=110 (per-model budget).
    k_acc = EFF['k_grid_acc']
    ki_acc = int(np.argmin(np.abs(k_acc - 110 * 2)))    # pair budget 220
    k_inet = EFF['k_grid']
    ki_inet = int(np.argmin(np.abs(k_inet - 110 * 2)))
    acc_at = np.nanmedian(EFF['acc_budget'][ki_acc])
    inet_at = np.nanmedian(EFF['inet_budget'][ki_inet])
    print(f'  budget @k~220: acc median={acc_at:.4f} vs inet best median={inet_at:.4f}')
    print('  heatmap_inet_avg shape:', EFF['heatmap_inet_avg'].shape,
          '| heatmap_smsc_avg shape:', EFF['heatmap_smsc_avg'].shape)

    for model_a, model_b in (('resnet50', 'resnet50_robust'), ('resnet50_clip', 'clipag_vitb32')):
        print('\n' + '=' * 68)
        print(f'build_pair({model_a}, {model_b}, ch=2)')
        print('=' * 68)
        PAIR = build_pair(model_a, model_b, ch=2, out_dir=args.out)
        print('  channel_label:', PAIR['channel_label'])
        print('  sweeps:', len(PAIR['sweeps_A']), '+', len(PAIR['sweeps_B']))
        print('  inet_predA range:', float(PAIR['inet_predA'].min()),
              float(PAIR['inet_predA'].max()))
        print('  inet_apref/bpref:', len(PAIR['inet_apref']), '/',
              len(PAIR['inet_bpref']),
              '| acc_apref/bpref:', len(PAIR['acc_apref']), '/',
              len(PAIR['acc_bpref']))
